x = int(input('Digite um valor x: '))
if x < 10:
    print("\033[1m" + "Tabuada do número" + "\033[0m", x)
    print(f"{x} x 1 = {x}")
    print(f"{x} x 2 = {x * 2}")
    print(f"{x} x 3 = {x * 3}")
    print(f"{x} x 4 = {x * 4}")
    print(f"{x} x 5 = {x * 5}")
    print(f"{x} x 6 = {x * 6}")
    print(f"{x} x 7 = {x * 7}")
    print(f"{x} x 8 = {x * 8}")
    print(f"{x} x 9 = {x * 9}")
    print(f"{x} x 10 = {x * 10}")
