a = int(input('Digite um valor A: '))
if a < 10:
    print("\033[1m" + "Tabuada do número" + "\033[0m", a)
    print(a ,'x 1 =', a)
    print(a ,'x 2 =', a * 2)
    print(a ,'x 3 =', a * 3)
    print(a ,'x 4 =', a * 4)
    print(a ,'x 5 =', a * 5)
    print(a ,'x 6 =', a * 6)
    print(a ,'x 7 =', a * 7)
    print(a ,'x 8 =', a * 8)
    print(a ,'x 9 =', a * 9)
    print(a ,'x 10 =', a * 10)
